### PR TITLE
DOCUMENT-81: Add installation instructions for Arch Linux

### PR DESCRIPTION
**Pull request by grafviktor**

### CODE REVIEW

**Comment by windx-foobar** [comment]
Hi. I think i can add deps `openssh-client` in build insturctions...
What other system dependencies are required for `goto`?

**Review by windx-foobar — CHANGES_REQUESTED** [review]
#83

**Comment by grafviktor** [comment]
> ... What other system dependencies are required for `goto`?
`goto` is statically linked, so there are no other deps apart from presence of `ssh` and `ssh-copy-id` in binary path.

**Comment by grafviktor** [comment]
Thank you very much for your contribution @windx-foobar 👍👍👍 All merged.

**Comment by grafviktor** [comment]
BTW, I prefer to name binary as just `gg` instead of `goto...`, as it's much faster to invoke it. And this is how it was done in the rpm and deb packages. But up to you 🙂

**Comment by windx-foobar** [comment]
> BTW, I prefer to name binary as just `gg` instead of `goto...`, as it's much faster to invoke it. And this is how it was done in the rpm and deb packages. But up to you 🙂

Yep, i see.
But its package save to files in /usr/bin
`gg-ssh` and `goto-ssh`
Postfix `-ssh` used cause `goto` already exists in `aur` repo 🙁

And the full name of the package is `goto-ssh-bin` cause your project is called `goto`, not `gg` ☺️

Me too call with `gg-ssh`

image

**Comment by grafviktor** [comment]
> 
> Yep, i see. But its package save `goto-ssh` and symlink `gg-ssh`->`goto-ssh` in /usr/bin. Postfix `-ssh` used cause `goto` already exists in `aur` repo 🙁
> 
Got you. You've already made a great analysis! 🙂

> 
> Thank u for approve. I hope someone besides me uses arch based distro 😀

My pleasure, mate. I'm sure, there are plenty of professional users who enjoy using Arch.

**Pull request merged**
